(* ::Package:: *)

(* ::Input:: *)
(*ClearAll["`*"];*)
(*sol1[n_]:=Module[{paths},*)
(*paths=FindHamiltonianCycle@Graph[*)
(*Apply[UndirectedEdge]/@Select[*)
(*Flatten[Table[{i,j},{i,n},{j,i-1}],1],*)
(*IntegerQ[Sqrt[Plus@@#]]&]];*)
(*If[Length[paths]==0,{},First/@First[paths]]];*)
(*sol1[32]*)
(*sol1[34]*)
(*sol1[15]*)
(**)
(*insert[cs_,bs_]:=Module[{*)
(*rs="",css=cs,bss=bs},*)
(*While[Length[css]>0,*)
(*If[First[css]=="?",*)
(*rs=rs<>ToString[First[bss]];bss=Rest[bss],*)
(*rs=rs<>First[css]];*)
(*css=Rest[css];*)
(*];rs];*)
(*sol2[s_]:=Module[{bs},*)
(*bs=Tuples[{0,1},Length[StringPosition[s,"?"]]];*)
(*insert[Characters[s],#]&/@bs];*)
(*sol2["01??0"]*)
(*sol2["010"]*)
(*sol2["???"]*)
(*sol2["1?10"]*)
(*sol2["1?1?0"]*)



