cabal-version:      3.0
name:               week387
version:            0.1.0.0
author:             pdcxs
maintainer:         pdcxs@outlook.com
build-type:         Simple

common warnings
    ghc-options: -Wall

executable week387
    import:           warnings
    main-is:          Main.hs
    other-modules:    Task1, Task2, Tests
    build-depends:    base,
                      containers
    hs-source-dirs:   app
    default-language: Haskell2010
