F₁ ← ▽=1⊕⊃(⧻|⊢)⊸⊛⊜□⊸(≠@ )⊂₃⊙" "
F₂ ← ▽⬚0×⊃(>0⊂0|>0)\+-⊸¬⊸=@(

┌─╴test
  ˙⍤ ≍ {"orange"} F₁"apple banana apple" "banana orange"
  ˙⍤ ≍ {"cat" "dog" "bird" "fish"} F₁"cat dog" "bird fish"
  ˙⍤ ≍ {"brown" "fox"} F₁"the quick brown fox" "the quick"
  ˙⍤ ≍ {} F₁"hello" "hello"
  ˙⍤ ≍ {"yellow"} F₁"blue blue red" "red green green yellow"
  ˙⍤ ≍ "" F₂"()()()"
  ˙⍤ ≍ "((()))" F₂"(((())))"
  ˙⍤ ≍ "()()()" F₂"(()())(())"
  ˙⍤ ≍ "(())" F₂"()((()))()"
  ˙⍤ ≍ "()(())()()" F₂"(()(()))(()())"
└─╴
